#pragma once

#include "../gl/glext.h"
#include "../gl/wglext.h"

/* GL_ARB_vertex_buffer_object */
PFNGLBINDBUFFERARBPROC           glBindBufferARB = NULL;
PFNGLDELETEBUFFERSARBPROC        glDeleteBuffersARB = NULL;
PFNGLGENBUFFERSPROC              glGenBuffersARB = NULL;
PFNGLISBUFFERARBPROC             glIsBufferARB = NULL;
PFNGLBUFFERDATAARBPROC           glBufferDataARB = NULL;
PFNGLBUFFERSUBDATAARBPROC        glBufferSubDataARB = NULL;
PFNGLGETBUFFERSUBDATAARBPROC     glGetBufferSubDataARB = NULL;
PFNGLMAPBUFFERARBPROC            glMapBufferARB = NULL;
PFNGLUNMAPBUFFERARBPROC          glUnmapBufferARB = NULL;
PFNGLGETBUFFERPARAMETERIVARBPROC glGetBufferParameterivARB = NULL;
PFNGLGETBUFFERPOINTERVARBPROC    glGetBufferPointervARB = NULL;

/* GL_ARB_multitexture */
PFNGLACTIVETEXTUREARBPROC        glActiveTextureARB = NULL;
PFNGLCLIENTACTIVETEXTUREARBPROC  glClientActiveTextureARB = NULL;
PFNGLMULTITEXCOORD1DARBPROC      glMultiTexCoord1dARB = NULL;
PFNGLMULTITEXCOORD1DVARBPROC     glMultiTexCoord1dvARB = NULL;
PFNGLMULTITEXCOORD1FARBPROC      glMultiTexCoord1fARB = NULL;
PFNGLMULTITEXCOORD1FVARBPROC     glMultiTexCoord1fvARB = NULL;
PFNGLMULTITEXCOORD1IARBPROC      glMultiTexCoord1iARB = NULL;
PFNGLMULTITEXCOORD1IVARBPROC     glMultiTexCoord1ivARB = NULL;
PFNGLMULTITEXCOORD1SARBPROC      glMultiTexCoord1sARB = NULL;
PFNGLMULTITEXCOORD1SVARBPROC     glMultiTexCoord1svARB = NULL;
PFNGLMULTITEXCOORD2DARBPROC      glMultiTexCoord2dARB = NULL;
PFNGLMULTITEXCOORD2DVARBPROC     glMultiTexCoord2dvARB = NULL;
PFNGLMULTITEXCOORD2FARBPROC      glMultiTexCoord2fARB = NULL;
PFNGLMULTITEXCOORD2FVARBPROC     glMultiTexCoord2fvARB = NULL;
PFNGLMULTITEXCOORD2IARBPROC      glMultiTexCoord2iARB = NULL;
PFNGLMULTITEXCOORD2IVARBPROC     glMultiTexCoord2ivARB = NULL;
PFNGLMULTITEXCOORD2SARBPROC      glMultiTexCoord2sARB = NULL;
PFNGLMULTITEXCOORD2SVARBPROC     glMultiTexCoord2svARB = NULL;
PFNGLMULTITEXCOORD3DARBPROC      glMultiTexCoord3dARB = NULL;
PFNGLMULTITEXCOORD3DVARBPROC     glMultiTexCoord3dvARB = NULL;
PFNGLMULTITEXCOORD3FARBPROC      glMultiTexCoord3fARB = NULL;
PFNGLMULTITEXCOORD3FVARBPROC     glMultiTexCoord3fvARB = NULL;
PFNGLMULTITEXCOORD3IARBPROC      glMultiTexCoord3iARB = NULL;
PFNGLMULTITEXCOORD3IVARBPROC     glMultiTexCoord3ivARB = NULL;
PFNGLMULTITEXCOORD3SARBPROC      glMultiTexCoord3sARB = NULL;
PFNGLMULTITEXCOORD3SVARBPROC     glMultiTexCoord3svARB = NULL;
PFNGLMULTITEXCOORD4DARBPROC      glMultiTexCoord4dARB = NULL;
PFNGLMULTITEXCOORD4DVARBPROC     glMultiTexCoord4dvARB = NULL;
PFNGLMULTITEXCOORD4FARBPROC      glMultiTexCoord4fARB = NULL;
PFNGLMULTITEXCOORD4FVARBPROC     glMultiTexCoord4fvARB = NULL;
PFNGLMULTITEXCOORD4IARBPROC      glMultiTexCoord4iARB = NULL;
PFNGLMULTITEXCOORD4IVARBPROC     glMultiTexCoord4ivARB = NULL;
PFNGLMULTITEXCOORD4SARBPROC      glMultiTexCoord4sARB = NULL;
PFNGLMULTITEXCOORD4SVARBPROC     glMultiTexCoord4svARB = NULL;

PFNGLATTACHSHADERPROC       glAttachShader      = NULL;
PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation= NULL;
PFNGLCOMPILESHADERPROC      glCompileShader     = NULL;
PFNGLCREATEPROGRAMPROC      glCreateProgram     = NULL;
PFNGLCREATESHADERPROC       glCreateShader      = NULL;
PFNGLDELETEPROGRAMPROC      glDeleteProgram     = NULL;
PFNGLDELETESHADERPROC       glDeleteShader      = NULL;
PFNGLDETACHSHADERPROC       glDetachShader      = NULL;
PFNGLISPROGRAMPROC          glIsProgram         = NULL;
PFNGLISSHADERPROC           glIsShader          = NULL;
PFNGLLINKPROGRAMPROC        glLinkProgram       = NULL;
PFNGLSHADERSOURCEPROC       glShaderSource      = NULL;
PFNGLUSEPROGRAMPROC         glUseProgram        = NULL;
PFNGLUNIFORM1FPROC          glUniform1f         = NULL;
PFNGLUNIFORM2FPROC          glUniform2f         = NULL;
PFNGLUNIFORM3FPROC          glUniform3f         = NULL;
PFNGLUNIFORM4FPROC          glUniform4f         = NULL;
PFNGLUNIFORM4FPROC          glUniform4fv        = NULL;
PFNGLUNIFORMMATRIX4FVPROC   glUniformMatrix4fv  = NULL;
PFNGLGETOBJECTPARAMETERFVARBPROC  glGetObjectParameterfvARB = NULL;
PFNGLGETOBJECTPARAMETERIVARBPROC  glGetObjectParameterivARB = NULL;
PFNGLGETINFOLOGARBPROC      glGetInfoLogARB     = NULL;
PFNGLGETSHADERIVPROC        glGetShaderiv       = NULL;
PFNGLGETSHADERINFOLOGPROC   glGetShaderInfoLog  = NULL;
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation= NULL;
PFNGLGENBUFFERSPROC         glGenBuffers        = NULL;
PFNGLBINDBUFFERPROC         glBindBuffer        = NULL;
PFNGLBUFFERDATAPROC         glBufferData        = NULL;
PFNGLGENVERTEXARRAYSPROC    glGenVertexArrays   = NULL;
PFNGLBINDVERTEXARRAYPROC    glBindVertexArray   = NULL;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = NULL;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray = NULL;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer = NULL;
PFNGLACTIVETEXTUREPROC      glActiveTexture     = NULL;
PFNGLGETATTRIBLOCATIONPROC  glGetAttribLocation = NULL;


/* WGL_EXT_swap_control */
PFNWGLSWAPINTERVALEXTPROC        wglSwapIntervalEXT = NULL;

/* WGL_EXT_extensions_string */
PFNWGLGETEXTENSIONSSTRINGARBPROC wglGetExtensionsStringARB = NULL;